import {
  solveBorderAlpha,
  solveForegroundSpec,
} from "./math.ts";
import type {
  BorderTargets,
  SolverConfig,
  SurfaceGroup,
  Theme,
} from "./types.ts";

export function toHighContrast(config: SolverConfig): SolverConfig {
  return {
    ...config,
    anchors: {
      ...config.anchors,
      keyColors: {}, // Force grayscale
      page: {
        ...config.anchors.page,
        light: {
          ...config.anchors.page.light,
          start: { background: 1.0, adjustable: false },
          end: { background: 0.0, adjustable: false },
        },
        dark: {
          ...config.anchors.page.dark,
          start: { background: 0.0, adjustable: false },
          end: { background: 1.0, adjustable: false },
        },
      },
      inverted: {
        ...config.anchors.inverted,
        light: {
          ...config.anchors.inverted.light,
          start: { background: 0.0, adjustable: false },
          end: { background: 1.0, adjustable: false },
        },
        dark: {
          ...config.anchors.inverted.dark,
          start: { background: 1.0, adjustable: false },
          end: { background: 0.0, adjustable: false },
        },
      },
    },
  };
}

export function generateTokensCss(
  groups: SurfaceGroup[],
  theme: Theme,
  borderTargets?: BorderTargets,
  selector?: string
): string {
  const rootLines: string[] = [];
  const propertyLines: string[] = [];
  const backgrounds = theme.backgrounds;

  rootLines.push("/* AUTO-GENERATED by src/lib/generator.ts */");

  // Note: We assume @property definitions are loaded via engine.css
  // Re-declaring them here causes transition glitches in some browsers
  // when the stylesheet is updated dynamically.

  const toNumber = (n: number): number => parseFloat(n.toFixed(4));

  // --- Primitives (Shadows & Focus) ---
  const rootSelector = selector || ":root";
  rootLines.push(`${rootSelector} {`);

  if (theme.primitives) {
    rootLines.push(`  /* Elevation */`);
    const { shadows, focus } = theme.primitives;

    // Shadows
    for (const [size, token] of Object.entries(shadows)) {
      rootLines.push(
        `  --shadow-${size}: light-dark(${token.light}, ${token.dark});`
      );
    }

    // Focus
    rootLines.push(`  /* Focus */`);
    rootLines.push(
      `  --focus-ring-color: light-dark(${focus.ring.light}, ${focus.ring.dark});`
    );
  }

  // Data Visualization Palette
  if (theme.charts && theme.charts.length > 0) {
    rootLines.push(`  /* Data Visualization */`);
    theme.charts.forEach((chart, index) => {
      rootLines.push(
        `  --chart-${index + 1}: light-dark(
    oklch(${toNumber(chart.light.l)} ${toNumber(chart.light.c)} ${toNumber(
          chart.light.h
        )}),
    oklch(${toNumber(chart.dark.l)} ${toNumber(chart.dark.c)} ${toNumber(
          chart.dark.h
        )})
  );`
      );
    });
  }

  rootLines.push(`}`);
  rootLines.push("");

  for (const group of groups) {
    for (const surface of group.surfaces) {
      const bgLight = backgrounds.get(surface.slug)?.light ?? {
        l: 0,
        c: 0,
        h: 0,
      };
      const bgDark = backgrounds.get(surface.slug)?.dark ?? {
        l: 0,
        c: 0,
        h: 0,
      };

      const lightSpec = solveForegroundSpec(bgLight.l);
      const darkSpec = solveForegroundSpec(bgDark.l);

      // Hue shift is already applied in solve()

      // Generate the Class Definition
      const prefix = selector ? `${selector} ` : "";
      let classSelector = `.surface-${surface.slug}`;

      // Special case: Apply 'page' surface tokens to body
      if (surface.slug === "page") {
        classSelector += ", body";
      }

      rootLines.push(`${prefix}${classSelector} {`);

      // 1. Surface Token
      rootLines.push(
        `  --surface-token: light-dark(
    oklch(${toNumber(bgLight.l)} ${toNumber(bgLight.c)} ${toNumber(bgLight.h)}),
    oklch(${toNumber(bgDark.l)} ${toNumber(bgDark.c)} ${toNumber(bgDark.h)})
  );`
      );

      // 2. Text Tokens
      rootLines.push(
        `  --text-high-token: light-dark(
    oklch(${toNumber(lightSpec["fg-high"])} 0 0),
    oklch(${toNumber(darkSpec["fg-high"])} 0 0)
  );`
      );

      rootLines.push(
        `  --text-subtle-token: light-dark(
    oklch(${toNumber(lightSpec["fg-subtle"])} 0 0),
    oklch(${toNumber(darkSpec["fg-subtle"])} 0 0)
  );`
      );

      rootLines.push(
        `  --text-subtlest-token: light-dark(
    oklch(${toNumber(lightSpec["fg-subtlest"])} 0 0),
    oklch(${toNumber(darkSpec["fg-subtlest"])} 0 0)
  );`
      );

      // 3. Border Tokens
      if (borderTargets) {
        const solveBorder = (
          bgL: number,
          textL: number,
          target: number
        ): number => solveBorderAlpha(bgL, textL, target);

        const lightDec = solveBorder(
          bgLight.l,
          lightSpec["fg-strong"],
          borderTargets.decorative
        );
        const darkDec = solveBorder(
          bgDark.l,
          darkSpec["fg-strong"],
          borderTargets.decorative
        );
        const lightInt = solveBorder(
          bgLight.l,
          lightSpec["fg-strong"],
          borderTargets.interactive
        );
        const darkInt = solveBorder(
          bgDark.l,
          darkSpec["fg-strong"],
          borderTargets.interactive
        );

        const lightBorderL = lightSpec["fg-strong"];
        const darkBorderL = darkSpec["fg-strong"];

        rootLines.push(
          `  --border-dec-token: light-dark(
    oklch(${toNumber(lightBorderL)} 0 0 / ${toNumber(lightDec)}),
    oklch(${toNumber(darkBorderL)} 0 0 / ${toNumber(darkDec)})
  );`
        );

        rootLines.push(
          `  --border-int-token: light-dark(
    oklch(${toNumber(lightBorderL)} 0 0 / ${toNumber(lightInt)}),
    oklch(${toNumber(darkBorderL)} 0 0 / ${toNumber(darkInt)})
  );`
        );
      }

      rootLines.push(`}`); // End class

      // States (Hover/Active)
      if (surface.states) {
        surface.states.forEach((state) => {
          const stateSlug = `${surface.slug}-${state.name}`;
          const bgState = backgrounds.get(stateSlug);

          if (bgState) {
            // We generate a modifier class? Or pseudo-class?
            // The config says "states: [{name: 'hover'}]".
            // Usually this maps to `.surface-card:hover`.
            // But sometimes it might be a class `.surface-card-selected`.
            // Let's assume pseudo-classes for standard names, and classes for others?
            // The original code generated `--surface-card-hover-token`.
            // And `utilities.css` mapped `.surface-card:hover` to that token.

            // Here we can generate:
            // .surface-card:hover { --surface-token: ... }

            const stateSelector =
              state.name === "hover" || state.name === "active"
                ? `.surface-${surface.slug}:${state.name}`
                : `.surface-${surface.slug}-${state.name}`; // e.g. .surface-card-selected

            rootLines.push(`${prefix}${stateSelector} {`);
            rootLines.push(
              `  --surface-token: light-dark(
    oklch(${toNumber(bgState.light.l)} ${toNumber(bgState.light.c)} ${toNumber(
                bgState.light.h
              )}),
    oklch(${toNumber(bgState.dark.l)} ${toNumber(bgState.dark.c)} ${toNumber(
                bgState.dark.h
              )})
  );`
            );
            rootLines.push(`}`);
          }
        });
      }
      rootLines.push("");
    }
  }

  return [...propertyLines, "", ...rootLines].join("\n");
}
