// Auto-generated by @axiomatic-design/color
// Do not edit directly

export const tokens = {
  /** Global shadow tokens */
  shadow: {
    sm: "var(--shadow-sm)",
    md: "var(--shadow-md)",
    lg: "var(--shadow-lg)",
    xl: "var(--shadow-xl)",
  },
  /** Global focus ring color */
  focus: "var(--focus-ring-color)",
  /** Data visualization palette */
  chart: {
    "1": "var(--chart-1)",
    "2": "var(--chart-2)",
    "3": "var(--chart-3)",
    "4": "var(--chart-4)",
    "5": "var(--chart-5)",
    "6": "var(--chart-6)",
    "7": "var(--chart-7)",
    "8": "var(--chart-8)",
    "9": "var(--chart-9)",
    "10": "var(--chart-10)",
  },
  /** Context-aware tokens (available inside a surface) */
  context: {
    surface: "var(--surface-token)",
    text: {
      high: "var(--text-high-token)",
      subtle: "var(--text-subtle-token)",
      subtlest: "var(--text-subtlest-token)",
    },
    border: {
      decorative: "var(--border-dec-token)",
      interactive: "var(--border-int-token)",
    },
  },
  /** Surface utility classes */
  surface: {
    page: "surface-page",
    workspace: "surface-workspace",
    card: "surface-card",
    action: "surface-action",
    spotlight: "surface-spotlight",
  },
} as const;

export type Tokens = typeof tokens;
