import type { ConfigOptions, Theme } from "../types.ts";

export function toTypeScript(theme: Theme, options?: ConfigOptions): string {
  const lines: string[] = [];
  const prefix = options?.prefix ? `${options.prefix}-` : "";
  const v = (name: string): string => `var(--${prefix}${name})`;

  lines.push(`// Auto-generated by @axiomatic-design/color`);
  lines.push(`// Do not edit directly`);
  lines.push(`/* eslint-disable @axiomatic-design/no-raw-tokens */`);
  lines.push(``);
  lines.push(`export const tokens = {`);

  // 1. Global Primitives
  lines.push(`  /** Global shadow tokens */`);
  lines.push(`  shadow: {`);
  for (const size of Object.keys(theme.primitives.shadows)) {
    lines.push(`    "${size}": "${v(`shadow-${size}`)}",`);
  }
  lines.push(`  },`);

  lines.push(`  /** Global focus ring color */`);
  lines.push(`  focus: "${v("focus-ring-color")}",`);

  if (theme.charts.length > 0) {
    lines.push(`  /** Data visualization palette */`);
    lines.push(`  chart: {`);
    theme.charts.forEach((_, index) => {
      lines.push(`    "${index + 1}": "${v(`chart-${index + 1}`)}",`);
    });
    lines.push(`  },`);
  }

  // 2. Context Tokens
  lines.push(`  /** Context-aware tokens (available inside a surface) */`);
  lines.push(`  context: {`);
  lines.push(`    surface: "${v("surface-token")}",`);
  lines.push(`    text: {`);
  lines.push(`      high: "${v("text-high-token")}",`);
  lines.push(`      subtle: "${v("text-subtle-token")}",`);
  lines.push(`      subtlest: "${v("text-subtlest-token")}",`);
  lines.push(`    },`);
  lines.push(`    border: {`);
  lines.push(`      decorative: "${v("border-dec-token")}",`);
  lines.push(`      interactive: "${v("border-int-token")}",`);
  lines.push(`    },`);
  lines.push(`  },`);

  // 3. Surface Classes
  lines.push(`  /** Surface utility classes */`);
  lines.push(`  surface: {`);
  for (const surface of theme.surfaces) {
    lines.push(`    "${surface.slug}": "surface-${surface.slug}",`);
  }
  lines.push(`  },`);

  lines.push(`} as const;`);
  lines.push(``);
  lines.push(`export type Tokens = typeof tokens;`);

  return lines.join("\n");
}
