import type { Theme } from "../types.ts";

export function toTypeScript(theme: Theme): string {
  const lines: string[] = [];

  lines.push(`// Auto-generated by @algebraic-systems/color-system`);
  lines.push(`// Do not edit directly`);
  lines.push(``);
  lines.push(`export const tokens = {`);

  // 1. Global Primitives
  lines.push(`  /** Global shadow tokens */`);
  lines.push(`  shadow: {`);
  for (const size of Object.keys(theme.primitives.shadows)) {
    lines.push(`    "${size}": "var(--shadow-${size})",`);
  }
  lines.push(`  },`);

  lines.push(`  /** Global focus ring color */`);
  lines.push(`  focus: "var(--focus-ring-color)",`);

  if (theme.charts.length > 0) {
    lines.push(`  /** Data visualization palette */`);
    lines.push(`  chart: {`);
    theme.charts.forEach((_, index) => {
      lines.push(`    "${index + 1}": "var(--chart-${index + 1})",`);
    });
    lines.push(`  },`);
  }

  // 2. Context Tokens
  lines.push(`  /** Context-aware tokens (available inside a surface) */`);
  lines.push(`  context: {`);
  lines.push(`    surface: "var(--surface-token)",`);
  lines.push(`    text: {`);
  lines.push(`      high: "var(--text-high-token)",`);
  lines.push(`      subtle: "var(--text-subtle-token)",`);
  lines.push(`      subtlest: "var(--text-subtlest-token)",`);
  lines.push(`    },`);
  lines.push(`    border: {`);
  lines.push(`      decorative: "var(--border-dec-token)",`);
  lines.push(`      interactive: "var(--border-int-token)",`);
  lines.push(`    },`);
  lines.push(`  },`);

  // 3. Surface Classes
  lines.push(`  /** Surface utility classes */`);
  lines.push(`  surface: {`);
  for (const surface of theme.surfaces) {
    lines.push(`    "${surface.slug}": "surface-${surface.slug}",`);
  }
  lines.push(`  },`);

  lines.push(`} as const;`);
  lines.push(``);
  lines.push(`export type Tokens = typeof tokens;`);

  return lines.join("\n");
}
