// Auto-generated by @axiomatic-design/color
// Do not edit directly
/* eslint-disable @axiomatic-design/no-raw-tokens */

export const tokens = {
  /** Global shadow tokens */
  shadow: {
    sm: "var(--axm-shadow-sm)",
    md: "var(--axm-shadow-md)",
    lg: "var(--axm-shadow-lg)",
    xl: "var(--axm-shadow-xl)",
  },
  /** Global focus ring color */
  focus: "var(--axm-focus-ring-color)",
  /** Data visualization palette */
  chart: {
    "1": "var(--axm-chart-1)",
    "2": "var(--axm-chart-2)",
    "3": "var(--axm-chart-3)",
    "4": "var(--axm-chart-4)",
    "5": "var(--axm-chart-5)",
    "6": "var(--axm-chart-6)",
    "7": "var(--axm-chart-7)",
    "8": "var(--axm-chart-8)",
    "9": "var(--axm-chart-9)",
    "10": "var(--axm-chart-10)",
  },
  /** Context-aware tokens (available inside a surface) */
  context: {
    surface: "var(--axm-surface-token)",
    text: {
      high: "var(--axm-text-high-token)",
      subtle: "var(--axm-text-subtle-token)",
      subtlest: "var(--axm-text-subtlest-token)",
    },
    border: {
      decorative: "var(--axm-border-dec-token)",
      interactive: "var(--axm-border-int-token)",
    },
  },
  /** Surface utility classes */
  surface: {
    page: "surface-page",
    workspace: "surface-workspace",
    card: "surface-card",
    action: "surface-action",
    "action-soft": "surface-action-soft",
    spotlight: "surface-spotlight",
    "status-success": "surface-status-success",
    "status-warning": "surface-status-warning",
    "status-error": "surface-status-error",
  },
} as const;

export type Tokens = typeof tokens;
