export const DataVizDemo = () => {
  // We assume 10 chart colors are generated by default
  const chartColors = Array.from({ length: 10 }, (_, i) => i + 1);

  return (
    <div className="docs-col">
      {/* Swatches */}
      <div className="docs-card">
        <strong className="docs-card-header">Palette Swatches</strong>
        <div
          style={{
            display: "grid",
            gridTemplateColumns: "repeat(auto-fill, minmax(60px, 1fr))",
            gap: "0.5rem",
          }}
        >
          {chartColors.map((i) => (
            <div
              key={i}
              style={{
                display: "flex",
                flexDirection: "column",
                gap: "0.25rem",
                alignItems: "center",
              }}
            >
              <div
                style={{
                  backgroundColor: `var(--chart-${i})`,
                  width: "100%",
                  aspectRatio: "1/1",
                  borderRadius: "6px",
                  boxShadow: "var(--shadow-sm)",
                  border: "1px solid var(--border-dec-token)",
                }}
              />
              <span
                style={{
                  fontSize: "0.7rem",
                  color: "var(--text-subtle-token)",
                  fontFamily: "var(--sl-font-mono)",
                }}
              >
                {i}
              </span>
            </div>
          ))}
        </div>
      </div>

      {/* Bar Chart */}
      <div className="docs-card">
        <strong className="docs-card-header">Bar Chart Example</strong>
        <div
          style={{
            height: "200px",
            display: "flex",
            alignItems: "flex-end",
            gap: "4px",
            paddingTop: "1rem",
          }}
        >
          {[60, 85, 40, 95, 55, 70, 30, 80, 45, 65].map((height, i) => (
            <div
              key={i}
              style={{
                flex: 1,
                height: `${height}%`,
                backgroundColor: `var(--chart-${(i % 10) + 1})`,
                borderRadius: "4px 4px 0 0",
                opacity: 0.9,
              }}
              title={`--chart-${(i % 10) + 1}`}
            />
          ))}
        </div>
      </div>

      {/* Pie Chart */}
      <div className="docs-card">
        <strong className="docs-card-header">Pie Chart Example</strong>
        <div
          style={{
            display: "flex",
            justifyContent: "center",
            padding: "1rem",
          }}
        >
          <div
            style={{
              width: "180px",
              height: "180px",
              borderRadius: "50%",
              background: `conic-gradient(
                  var(--chart-1) 0% 20%,
                  var(--chart-2) 20% 35%,
                  var(--chart-3) 35% 55%,
                  var(--chart-4) 55% 80%,
                  var(--chart-5) 80% 100%
                )`,
              boxShadow: "var(--shadow-md)",
              border: "1px solid var(--border-dec-token)",
            }}
          />
        </div>
      </div>
    </div>
  );
};
