export const DynamicRange = () => {
  return (
    <div
      className="docs-grid docs-mb-4"
      style={{
        display: "grid",
        gridTemplateColumns: "repeat(auto-fit, minmax(280px, 1fr))",
        gap: "1.5rem",
        marginTop: "1.5rem",
      }}
    >
      <RangeCard
        title="Light Mode (Dimming)"
        description="Page starts bright. Surfaces get darker to create separation."
        mode="light"
      />
      <RangeCard
        title="Dark Mode (Illumination)"
        description="Page starts dark. Surfaces get lighter to approach the light source."
        mode="dark"
      />
    </div>
  );
};

const RangeCard = ({
  title,
  description,
  mode,
}: {
  title: string;
  description: string;
  mode: "light" | "dark";
}) => {
  const isLight = mode === "light";

  // Surfaces configuration
  // We use the class names generated by the system
  const surfaces = isLight
    ? [
        {
          name: "Page",
          className: "surface-page",
          label: "Start",
        },
        {
          name: "Card",
          className: "surface-card",
          label: "Mid",
        },
        {
          name: "Sidebar",
          className: "surface-workspace",
          label: "End",
        },
      ]
    : [
        {
          name: "Sidebar",
          className: "surface-workspace",
          label: "End",
        },
        {
          name: "Card",
          className: "surface-card",
          label: "Mid",
        },
        {
          name: "Page",
          className: "surface-page",
          label: "Start",
        },
      ];

  return (
    <div
      className="docs-card"
      style={{
        // Force the color scheme for this card
        colorScheme: mode,
        border: "1px solid var(--sl-color-gray-5)",
        borderRadius: "8px",
        overflow: "hidden",
        background: "var(--sl-color-bg-nav)",
        boxShadow: "var(--sl-shadow-sm)",
      }}
    >
      <div
        style={{
          padding: "1rem",
          borderBottom: "1px solid var(--sl-color-gray-5)",
        }}
      >
        <strong
          style={{
            display: "block",
            marginBottom: "0.5rem",
            color: "var(--sl-color-text)",
          }}
        >
          {title}
        </strong>
        <p
          style={{
            margin: 0,
            fontSize: "0.9em",
            color: "var(--sl-color-text-gray)",
            lineHeight: 1.4,
          }}
        >
          {description}
        </p>
      </div>

      <div
        className="surface-page"
        style={{
          position: "relative",
          height: "220px",
          // Use the surface token for background
          background: "var(--surface-token)",
          color: "var(--text-high-token)",
          padding: "2rem",
        }}
      >
        {/* Range Indicator Line - Simplified to a solid line for now as we can't easily gradient between scoped vars */}
        <div
          style={{
            position: "absolute",
            left: "1.5rem",
            top: "2.5rem",
            bottom: "2.5rem",
            width: "4px",
            background: "var(--border-dec-token)",
            borderRadius: "2px",
          }}
        />

        {/* Anchors Labels */}
        <div
          style={{
            position: "absolute",
            left: "2.5rem",
            top: "2rem",
            fontSize: "0.75em",
            fontWeight: "bold",
            color: "var(--text-subtle-token)",
            fontFamily: "var(--sl-font-mono)",
          }}
        >
          {isLight ? "Start" : "End"}
        </div>
        <div
          style={{
            position: "absolute",
            left: "2.5rem",
            bottom: "2rem",
            fontSize: "0.75em",
            fontWeight: "bold",
            color: "var(--text-subtle-token)",
            fontFamily: "var(--sl-font-mono)",
          }}
        >
          {isLight ? "End" : "Start"}
        </div>

        {/* Stack Visualization */}
        <div
          style={{
            marginLeft: "5rem",
            display: "flex",
            flexDirection: "column",
            height: "100%",
            justifyContent: "space-between",
            gap: "0.5rem",
          }}
        >
          {surfaces.map((s, i) => (
            <div
              key={i}
              className={s.className}
              style={{
                background: "var(--surface-token)",
                border: "1px solid var(--border-dec-token)",
                borderRadius: "6px",
                padding: "0 1rem",
                color: "var(--text-high-token)",
                fontSize: "0.85em",
                fontWeight: 500,
                boxShadow: "var(--shadow-sm)",
                display: "flex",
                justifyContent: "space-between",
                alignItems: "center",
                flex: 1,
              }}
            >
              <span>{s.name}</span>
              <span
                style={{
                  opacity: 0.5,
                  fontSize: "0.9em",
                  fontFamily: "var(--sl-font-mono)",
                }}
              >
                {/* We don't have the exact L value available in CSS var, so we omit it or use a placeholder if needed */}
              </span>
            </div>
          ))}
        </div>
      </div>
    </div>
  );
};
